# File specifying the environment and algorithm configuration
env_config:
  timestep: 0.1
  seed: 42
  IC:
    - 2000  # x
    - -1600 # y
    - 0   # z
    - -90   # vx
    - 180   # vy
    - 0     # vz
    - 0.866
    - 0
    - 0
    - -0.5
    - 0
    - 0
    - 0
    - 41.0E+3
  
  ICRange:
    - 10
    - 200
    - 0
    - 30
    - 30
    - 0
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.05
    - 0.05
    - 0.05
    - 1.0E+3
  
  reward_coeff: 
    alfa: -0.01
    beta: -1.0E-8
    delta: -5
    eta: 0.1
    gamma: -1
    kappa: 10
    xi: 0.004
    w_final : 50
    max_r_f: 100
    max_v_f: 50

  trajectory_limits: 
    attitude_limit: [360,85,85,]
  
  landing_params: 
    waypoint: 50
    landing_radius: 50
    maximum_velocity: 15
    landing_attitude_limit: [360,10,10,]
    # [XYZ] intrinsic rotation order i.e. yaw,pitch,roll
    omega_lim: [0.2, 0.2, 0.2]      
  reward_shaping_type: 'acceleration'

sb3_config: 
    env_id: "my_environment/Falcon6DOF-v0"
    policy_type: "MlpPolicy"
    total_timesteps: 20.0E+6
    max_time: 150