# File specifying the environment and algorithm configuration
env_config:
  timestep: 0.1
  seed: 42
  IC:
    - 500  # x
    - 100 # y
    - 100   # z
    - -50   # vx
    - 0   # vy
    - 0     # vz
    - 1
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 41.0E+3
  
  ICRange:
    - 50
    - 10
    - 10
    - 10
    - 10
    - 10
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.05
    - 0.05
    - 0.05
    - 1.0E+3
  
  reward_coeff: 
    alfa: -0.01
    beta: -1.0E-7
    delta: -5
    eta: 0.05
    gamma: -10
    kappa: 10
    xi: 0.004
    w_r_f : 0       # SET TO 0 TO DISABLE TERMINAL REWARD
    w_v_f : 0.5       # SET TO 0 TO DISABLE TERMINAL REWARD
    max_r_f: 100
    max_v_f: 75

  trajectory_limits: 
    attitude_limit: [85, 85, 360]
  
  landing_params: 
    waypoint: 50
    landing_radius: 30
    maximum_velocity: 10
    landing_attitude_limit: [10 , 10, 360,]
    # [Yaw, Pitch, Roll] in DEG,
    # rotations order zyx
    # VISUALIZATION:
    # https://bit.ly/3CoEdvH
    omega_lim: [0.2, 0.2, 0.2]      

sb3_config: 
    env_id: "my_environment/Falcon6DOF-v0"
    policy_type: "MlpPolicy"
    total_timesteps: 1.0E+6
    max_time: 80
