# File specifying the environment and algorithm configuration
env_config:
  timestep: 0.1
  seed: 42
  IC:
    - 2000  # x
    - -1600 # y
    - 0   # z
    - -90   # vx
    - 180   # vy
    - 0     # vz
    - 0.866
    - 0
    - 0
    - -0.5
    - 0
    - 0
    - 0
    - 41.0E+3
  ICRange:
    - 10
    - 200
    - 0
    - 30
    - 30
    - 0
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.05
    - 0.05
    - 0.05
    - 1.0E+3
  reward_coeff: 
    alfa: -0.01
    beta: -1.0E-8
    delta: -5
    eta: 0.1
    gamma: -10
    kappa: 10
    xi: 0.004
    w_r_f : 0.1       # SET TO 0 TO DISABLE TERMINAL REWARD
    w_v_f : 0.8       # SET TO 0 TO DISABLE TERMINAL REWARD
    max_r_f: 100
    max_v_f: 30
                        
  trajectory_limits: 
    attitude_limit: [85, 85, 360]
  landing_params: 
    waypoint: -1
    landing_radius: 50
    maximum_velocity: 10
    landing_attitude_limit: [10 , 10, 360,]
    # [Yaw, Pitch, Roll] in DEG,
    # rotations order zyx
    # VISUALIZATION:
    # https://bit.ly/3CoEdvH
    omega_lim: [0.2, 0.2, 0.2]      

sb3_config: 
    env_id: "my_environment/Falcon6DOF-v0"
    policy_type: "MlpPolicy"
    total_timesteps: 12.0E+6
    max_time: 150
